spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      nacos:
        enabled: true
      cache:
        enabled: false
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: login_route
          uri: lb://auth
          order: 1
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, localhost:8080,

        - id: appMain_route
          uri: lb://appMain
          order: 1
          predicates:
            - Path=/api/appMain/**
          filters:
            - StripPrefix=2
            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, localhost:8080,

        - id: id_route
          uri: fs://IDServer
          order: 1
          predicates:
            - Path=/id/**
          filters:
            - StripPrefix=1

        - id: root_route
          uri: http://localhost:4173/
          order: 1000
          predicates:
            - Path=/**