spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: login_route
          uri: lb://auth
          order: 1
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, localhost:8080,
        - id: root_route
          uri: http://localhost:4173/
          order: 1000
          predicates:
            - Path=/**
