spring:
  application:
    name: fileServer
  redis:
    port: 6379
    host: localhost
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 172.17.0.3
    port: 5672
    username: guest
    password: guest

server:
  port: 5615

clouddrive:
  save-path: E:\file
  buffer-path: E:\buffer