spring:
  application:
    name: fileServer
  redis:
    port: 6379
    host: localhost
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 5615

rocketmq:
  name-server: 172.17.0.1:9876
  producer:
    group: cloudDriveFileCore
    send-message-timeout: 10000

clouddrive:
  save-path: E:\file
  buffer-path: E:\buffer